### PR TITLE
Added Styling, Removed Back Buttons, Renamed Files, and Redid Logo

### PR DESCRIPTION
**Pull request by ConnerConnerConner**
I made it looks good ig

### CODE REVIEW

**Comment by NoobJsPerson** [comment]
i dont know if the site necessarily needs better styling for the moment, also inputs have no outlines in bright mode and textareas are not effected by dark mode and git pull everytime theres commits ahead because it fixes issues with the site. ill ask other contributers to see if its worth merging
generally thank you for your efforts :)

**Comment by ConnerConnerConner** [comment]
Thank you for your reply, I fixed the issues with the textareas (It was just a typo) and I made the Input Boxes more obvious that they're input boxes, I didn't add the outlines because I want everything to look like they fit there. I also did a git pull and un-renamed the files. I also instead of removing the back buttons I fixed them so if you would like I could make another pull request

**Comment by NoobJsPerson** [comment]
yeah of course id like you to open a new one or just use this one, last time i checked retiming was broken on your fork but i think i can help you fix that. (overall i really like your design)

**Comment by NoobJsPerson** [comment]
nvm retiming seems to work. could u git pull one more time and rename afterwards, itll be ready to merge then

**Comment by ConnerConnerConner** [comment]
I'll fix that, I also need to make sure the spacing is good on mobile

**Pull request closed without merging**
