### PR TITLE
Settings v2

### PR DESCRIPTION
**Pull request by badonyt**
**Better** **settings**, now its more **clear** what is able to be **written**, and a **reset** back to **default**

### CODE REVIEW

**Comment by badonyt** [comment]
Also when im testing, i cant go back home even doe i didnt change anything in that area

**Comment by NoobJsPerson** [comment]
Also the reason that you can't go back home is the redirect code lines are written to work with GitHub pages that adds a `/speedrun-timer` to the sites path thats why it doesn't work while testing locally. So don't worry about it too much

**Comment by badonyt** [comment]
i allowed

imagem

**Comment by badonyt** [comment]
i think you have to be assigned, just a guess

imagem

**Pull request merged**
