### PR TITLE
Added an old css option

### PR DESCRIPTION
**Pull request by badonyt**
I personally dont like the new css. I prefer the old one. So i added an option for the old one.

### CODE REVIEW

**Comment by badonyt** [comment]
Added more sensible names to localstorage css since i was confused of my own code.

**Review by badonyt — COMMENTED** [review]
Removed one line of code in credits

**Comment by badonyt** [comment]
Are you going to merge?

**Comment by NoobJsPerson** [comment]
sorry merging this doesnt seem viable at this point

**Pull request closed without merging**
